logging:
  level: INFO
  loggers:
    io.dropwizard: INFO
  file:
    enable: true
    currentLogFilename: ./logs/application.log
    threshold: ALL
    archive: true
    archivedLogFilenamePattern: ./logs/application-%d.log
    archivedFileCount: 5
    timeZone: UTC

database:
  driverClass: org.mysql.jdbc.Driver
  user: root
  password:
  url: jdbc:mysql://localhost/wechat?useUnicode=true&characterEncoding=utf-8
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute