cache:
  label: 3600

database:
  driverClass: com.mysql.jdbc.Driver
  url: 'jdbc:mysql://localhost/wechat'
  user: root

logging:
  level: INFO
  loggers:
    io.dropwizard: INFO
  appenders:
    - type: file
      currentLogFilename: ./logs/application.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: ./logs/application-%d.log
      archivedFileCount: 5
      timeZone: UTC
